name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: ./.github/workflows/reusable-build.yml
    with:
      publish: true
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
