name: Reusable Build

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
    secrets:
      PYPI_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          make install_dev

      - name: Lint
        run: |
          make lint
          make typecheck

      - name: Test with pytest
        run: |
          make test

      - name: Build package
        run: |
          make build

      - name: Publish to PyPI
        if: inputs.publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          make publish
